# Generated by Django 3.2.3 on 2021-05-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_alter_group_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='picture',
            field=models.CharField(blank=True, max_length=250, verbose_name='Клуб логотипі'),
        ),
    ]
