# Generated by Django 3.2.3 on 2021-05-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.CharField(default='Белгісіз сайт әкімшісіне хабарлаңыз', max_length=50, verbose_name='Уақыт'),
        ),
    ]
