# Generated by Django 3.2.8 on 2021-12-27 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210528_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Мәтін')),
                ('image_base64', models.TextField(verbose_name='Сурет (Base64)')),
                ('youtube_link', models.TextField(verbose_name='Видео (Ютуб)')),
                ('date', models.CharField(default='Белгісіз сайт әкімшісіне хабарлаңыз', max_length=50, verbose_name='Уақыт')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'жаңалық',
                'verbose_name_plural': 'жаңалықтар',
            },
        ),
    ]
