# Generated by Django 3.2.3 on 2021-05-23 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day', models.CharField(max_length=20, verbose_name='туылға күні')),
                ('birth_mounth', models.CharField(max_length=20, verbose_name='туылға айы')),
                ('birth_year', models.CharField(max_length=20, verbose_name='туылға жылы')),
                ('circle', models.CharField(default='Белгісіз', max_length=250, verbose_name='Клуб')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
